import "./style.css";

type Site={id:string,name:string,url:string,search:string,enabled:boolean};
type Item={id:string,title:string,url:string,image:string,source:string};
const seed:Site[]=[
{id:"unsplash",name:"Unsplash",url:"https://unsplash.com",search:"https://unsplash.com/s/photos/{keyword}",enabled:true},
{id:"pexels",name:"Pexels",url:"https://www.pexels.com",search:"https://www.pexels.com/search/{keyword}/",enabled:true},
{id:"pinterest",name:"Pinterest",url:"https://www.pinterest.com",search:"https://www.pinterest.com/search/pins/?q={keyword}",enabled:true},
{id:"behance",name:"Behance",url:"https://www.behance.net",search:"https://www.behance.net/search/projects?search={keyword}",enabled:true},
{id:"dribbble",name:"Dribbble",url:"https://dribbble.com",search:"https://dribbble.com/search/{keyword}",enabled:true}
];
const S={sites:"mh-sites",fav:"mh-fav",hist:"mh-hist",theme:"mh-theme"};
let sites:Site[]=JSON.parse(localStorage.getItem(S.sites)||"null")||seed;
let fav:Item[]=JSON.parse(localStorage.getItem(S.fav)||"[]");
let hist:string[]=JSON.parse(localStorage.getItem(S.hist)||"[]");
let q=""; let theme=localStorage.getItem(S.theme)||"light";
const save=()=>{localStorage.setItem(S.sites,JSON.stringify(sites));localStorage.setItem(S.fav,JSON.stringify(fav));localStorage.setItem(S.hist,JSON.stringify(hist));localStorage.setItem(S.theme,theme)};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const url=(s:Site,k:string)=>s.search.replaceAll("{keyword}",encodeURIComponent(k.trim()));
function layout(body:string){document.querySelector("#root")!.innerHTML=`<div class="app ${theme}"><aside><div class="brand"><div class="logo">M</div><div><strong>Material Hub</strong><small>Designer Search</small></div></div><nav><button data-page="search" class="active">⌕ <span>素材搜索</span></button><button data-page="favorites">☆ <span>我的收藏</span><i>${fav.length}</i></button><button data-page="history">◷ <span>搜索历史</span></button><button data-page="sites">⊞ <span>素材网站</span></button></nav><div class="bottom"><button id="theme">◐ 外观</button><small>Material Hub 0.1.1</small></div></aside><main><header><div class="search"><span>⌕</span><input id="q" placeholder="搜索图片、海报、UI、插画、3D……" value="${esc(q)}"><button id="go">搜索</button></div></header><div id="body">${body}</div></main></div>`;bind()}
function searchPage(){return `<section class="hero"><label>MATERIAL HUB</label><h1>找到你的设计灵感</h1><p>一次输入，快速访问多个素材来源。</p></section><div class="chips">${sites.map((s,i)=>`<label><input data-si="${i}" type="checkbox" ${s.enabled?"checked":""}>${esc(s.name)}</label>`).join("")}</div><div class="quick">${["东方美学","新中式海报","美容院画册","3D人物","花灯夜景","高级感背景"].map(x=>`<button data-q="${esc(x)}">${x}</button>`).join("")}</div><div id="results" class="grid"><div class="empty"><b>输入关键词开始搜索</b><span>支持 Enter 快速搜索</span></div></div>`}
function doSearch(){q=(document.querySelector("#q") as HTMLInputElement)?.value.trim()||q;if(!q)return;hist=[q,...hist.filter(x=>x!==q)].slice(0,30);save();const on=sites.filter(s=>s.enabled);document.querySelector("#results")!.innerHTML=on.length?on.map(s=>`<article class="card"><div class="preview"><span>↗</span></div><div class="cardtext"><div class="source">${esc(s.name)}<small>素材网站</small></div><strong>${esc(q)}</strong><p>在 ${esc(s.name)} 搜索相关素材</p><button class="primary" data-open="${esc(url(s,q))}">打开搜索结果</button></div></article>`).join(""):`<div class="empty"><b>没有启用的网站</b><span>前往“素材网站”开启来源。</span></div>`;document.querySelectorAll<HTMLButtonElement>("[data-open]").forEach(b=>b.onclick=()=>window.open(b.dataset.open,"_blank"))}
function favoritesPage(){return `<section class="title"><label>LIBRARY</label><h2>我的收藏</h2><p>本地保存的灵感与素材入口。</p></section><div class="grid">${fav.length?fav.map((x,i)=>`<article class="card fav"><div class="preview"><span>☆</span></div><div class="cardtext"><div class="source">${esc(x.source)}</div><strong>${esc(x.title)}</strong><button data-del="${i}">移除收藏</button></div></article>`).join(""):`<div class="empty"><b>还没有收藏</b><span>图片 API 接入后可直接收藏图片。</span></div>`}</div>`}
function historyPage(){return `<section class="title"><label>HISTORY</label><h2>搜索历史</h2><p>最近搜索的关键词。</p></section><div class="history">${hist.length?hist.map(x=>`<button data-h="${esc(x)}">${esc(x)}<span>↗</span></button>`).join(""):`<div class="empty"><b>暂无搜索历史</b></div>`}</div>`}
function sitesPage(){return `<section class="title"><label>SOURCES</label><h2>素材网站</h2><p>自己添加搜索来源，软件不会把网站写死。</p></section><div class="sites">${sites.map((s,i)=>`<div class="site"><div><strong>${esc(s.name)}</strong><small>${esc(s.url)}</small><code>${esc(s.search)}</code></div><label class="toggle"><input data-toggle="${i}" type="checkbox" ${s.enabled?"checked":""}><i></i></label><button data-remove="${i}">删除</button></div>`).join("")}</div><div class="add"><h3>＋ 添加素材网站</h3><div><input id="sn" placeholder="网站名称"><input id="su" placeholder="网站地址"><input id="ss" placeholder="搜索地址，关键词用 {keyword}"><button id="add">添加</button></div></div>`}
function bind(){document.querySelectorAll<HTMLButtonElement>("[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-page]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=b.dataset.page!;document.querySelector("#body")!.innerHTML=p==="search"?searchPage():p==="favorites"?favoritesPage():p==="history"?historyPage():sitesPage();bindBody()});document.querySelector("#go")?.addEventListener("click",doSearch);document.querySelector("#q")?.addEventListener("keydown",e=>{if(e.key==="Enter")doSearch()});document.querySelector("#theme")?.addEventListener("click",()=>{theme=theme==="light"?"dark":"light";save();layout(searchPage())});bindBody()}
function bindBody(){document.querySelectorAll<HTMLInputElement>("[data-si]").forEach(x=>x.onchange=()=>{sites[+x.dataset.si!].enabled=x.checked;save()});document.querySelectorAll<HTMLButtonElement>("[data-q]").forEach(b=>b.onclick=()=>{q=b.dataset.q!;layout(searchPage());doSearch()});document.querySelectorAll<HTMLButtonElement>("[data-h]").forEach(b=>b.onclick=()=>{q=b.dataset.h!;layout(searchPage());doSearch()});document.querySelectorAll<HTMLButtonElement>("[data-del]").forEach(b=>b.onclick=()=>{fav.splice(+b.dataset.del!,1);save();layout(favoritesPage())});document.querySelectorAll<HTMLInputElement>("[data-toggle]").forEach(x=>x.onchange=()=>{sites[+x.dataset.toggle!].enabled=x.checked;save()});document.querySelectorAll<HTMLButtonElement>("[data-remove]").forEach(b=>b.onclick=()=>{sites.splice(+b.dataset.remove!,1);save();layout(sitesPage())});document.querySelector("#add")?.addEventListener("click",()=>{const n=(document.querySelector("#sn") as HTMLInputElement).value.trim(),u=(document.querySelector("#su") as HTMLInputElement).value.trim(),s=(document.querySelector("#ss") as HTMLInputElement).value.trim();if(n&&u&&s){sites.push({id:crypto.randomUUID(),name:n,url:u,search:s,enabled:true});save();layout(sitesPage())}})}
layout(searchPage());