import "./style.css";
import {searchOpenverse,type ImageItem} from "./adapters/openverse";
import {downloadImage,copyImageUrl} from "./download";
import {getCollections,addCollection,removeCollection,type Collection} from "./favorites";
type Site={id:string,name:string,url:string,search:string,enabled:boolean};
type Saved=ImageItem&{collections?:string[];tags?:string[];savedAt?:number};
const seed:Site[]=[{id:"openverse",name:"Openverse",url:"https://openverse.org",search:"",enabled:true},{id:"unsplash",name:"Unsplash",url:"https://unsplash.com",search:"https://unsplash.com/s/photos/{keyword}",enabled:true},{id:"pexels",name:"Pexels",url:"https://www.pexels.com",search:"https://www.pexels.com/search/{keyword}/",enabled:true},{id:"pinterest",name:"Pinterest",url:"https://www.pinterest.com",search:"https://www.pinterest.com/search/pins/?q={keyword}",enabled:true}];
const K={sites:"mh-sites",fav:"mh-fav",hist:"mh-hist",theme:"mh-theme"};
let sites:Site[]=JSON.parse(localStorage.getItem(K.sites)||"null")||seed,fav:Saved[]=JSON.parse(localStorage.getItem(K.fav)||"[]"),hist:string[]=JSON.parse(localStorage.getItem(K.hist)||"[]"),q="",theme=localStorage.getItem(K.theme)||"light",page=1,busy=false,collection="all";
const save=()=>{localStorage.setItem(K.sites,JSON.stringify(sites));localStorage.setItem(K.fav,JSON.stringify(fav));localStorage.setItem(K.hist,JSON.stringify(hist));localStorage.setItem(K.theme,theme)};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const favd=(id:string)=>fav.some(x=>x.id===id);
const itemFromCard=(c:Element):Saved=>{const img=c.querySelector('img') as HTMLImageElement;const id=(c.querySelector('[data-fav]') as HTMLElement)?.dataset.fav||crypto.randomUUID();return {id,title:c.querySelector('strong')?.textContent||'Untitled',image:img.dataset.full||img.src,thumbnail:img.src,source:c.querySelector('small')?.textContent||'Openverse',page:img.dataset.page||img.src,collections:['all'],savedAt:Date.now()}};
function shell(body:string){document.querySelector('#root')!.innerHTML=`<div class="app ${theme}"><aside><div class="brand"><div class="logo">M</div><div><strong>Material Hub</strong><small>Designer Search</small></div></div><nav><button data-page="search">⌕ <span>素材搜索</span></button><button data-page="favorites">☆ <span>我的收藏</span><i>${fav.length}</i></button><button data-page="history">◷ <span>搜索历史</span></button><button data-page="sites">⊞ <span>素材网站</span></button></nav><div class="bottom"><button id="theme">◐ 外观</button></div></aside><main><header><div class="search"><span>⌕</span><input id="q" value="${esc(q)}" placeholder="搜索图片、海报、UI、插画、3D……"><button id="go">搜索</button></div></header><div id="body">${body}</div></main></div>`;bind()}
function searchPage(){return `<section class="hero"><label>MATERIAL HUB</label><h1>找到你的设计灵感</h1><p>统一搜索开放图片素材，支持 Enter。</p></section><div class="chips">${sites.map((s,i)=>`<label><input data-site="${i}" type="checkbox" ${s.enabled?'checked':''}>${esc(s.name)}</label>`).join('')}</div><div class="quick">${['东方美学','新中式海报','美容院画册','3D人物','花灯夜景','高级感背景'].map(x=>`<button data-q="${esc(x)}">${x}</button>`).join('')}</div><div id="results" class="grid"><div class="empty"><b>输入关键词开始搜索</b><span>结果会直接显示在这里</span></div></div>`}
function card(x:Saved){return `<article class="image-card"><button class="image-wrap" data-openimg="${esc(x.id)}"><img loading="lazy" src="${esc(x.thumbnail||x.image)}" data-full="${esc(x.image)}" data-page="${esc(x.page||x.image)}" alt="${esc(x.title)}"></button><div class="image-info"><div><strong title="${esc(x.title)}">${esc(x.title||'Untitled')}</strong><small>${esc(x.source||'Openverse')}${x.author?' · '+esc(x.author):''}</small></div><button class="star ${favd(x.id)?'on':''}" data-fav="${esc(x.id)}">${favd(x.id)?'★':'☆'}</button></div></article>`}
async function search(reset=true){q=(document.querySelector('#q') as HTMLInputElement)?.value.trim()||q;if(!q||busy)return;if(reset){page=1;hist=[q,...hist.filter(x=>x!==q)].slice(0,30);save()}busy=true;const r=document.querySelector('#results')!;if(reset)r.innerHTML='<div class="empty"><b>正在搜索…</b><span>正在获取图片</span></div>';try{const items=await searchOpenverse(q,page);if(reset)r.innerHTML=items.map(x=>card(x)).join('')||'<div class="empty"><b>没有找到结果</b></div>';else r.insertAdjacentHTML('beforeend',items.map(x=>card(x)).join(''));document.querySelector('#more')?.remove();if(items.length>=30)r.insertAdjacentHTML('afterend','<button id="more" class="more">加载更多</button>');bindBody()}catch{if(reset)r.innerHTML='<div class="empty"><b>搜索失败</b><span>请检查网络后重试</span></div>'}finally{busy=false}}
function toggle(x:Saved){if(favd(x.id))fav=fav.filter(y=>y.id!==x.id);else fav=[{...x,collections:['all'],savedAt:Date.now()},...fav];save()}
function favoritesPage(){const cols=getCollections(),list=collection==='all'?fav:fav.filter(x=>x.collections?.includes(collection));return `<section class="title"><label>LIBRARY</label><h2>我的收藏</h2><p>按分类管理你的设计素材。</p></section><div class="chips collection-chips">${cols.map(c=>`<button class="quick buttonlike ${c.id===collection?'selected':''}" data-col="${esc(c.id)}">📁 ${esc(c.name)}${c.id==='all'?` (${fav.length})`:''}</button>`).join('')}<button class="quick buttonlike" id="newcol">＋ 新建分类</button></div><div class="grid">${list.length?list.map(card).join(''):'<div class="empty"><b>这个分类还没有素材</b><span>右键图片可以收藏到分类</span></div>'}</div>`}
function historyPage(){return `<section class="title"><label>HISTORY</label><h2>搜索历史</h2></section><div class="history">${hist.length?hist.map(x=>`<button data-h="${esc(x)}">${esc(x)}<span>↗</span></button>`).join(''):'<div class="empty"><b>暂无搜索历史</b></div>'}</div>`}
function sitesPage(){return `<section class="title"><label>SOURCES</label><h2>素材网站</h2><p>可继续添加普通搜索入口。</p></section><div class="sites">${sites.map((s,i)=>`<div class="site"><div><strong>${esc(s.name)}</strong><small>${esc(s.url)}</small><code>${s.search?esc(s.search):'内置 API 适配器'}</code></div><label class="toggle"><input data-toggle="${i}" type="checkbox" ${s.enabled?'checked':''}><i></i></label>${s.id!=='openverse'?`<button data-remove="${i}">删除</button>`:''}</div>`).join('')}</div><div class="add"><h3>＋ 添加素材网站</h3><div><input id="sn" placeholder="网站名称"><input id="su" placeholder="网站地址"><input id="ss" placeholder="搜索地址，关键词用 {keyword}"><button id="add">添加</button></div></div>`}
function assignCollection(x:Saved){const cols=getCollections();const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-bg"></div><div class="modal-box smallbox"><button class="close">×</button><h3>收藏到分类</h3><div class="collection-list">${cols.filter(c=>c.id!=='all').map(c=>`<button data-assign="${esc(c.id)}">📁 ${esc(c.name)}${x.collections?.includes(c.id)?' ✓':''}</button>`).join('')}</div><button id="newc" class="newcat">＋ 新建分类</button></div>`;document.body.appendChild(m);m.querySelector('.close')!.addEventListener('click',()=>m.remove());m.querySelector('.modal-bg')!.addEventListener('click',()=>m.remove());m.querySelectorAll<HTMLButtonElement>('[data-assign]').forEach(b=>b.onclick=()=>{const id=b.dataset.assign!;const s=fav.find(y=>y.id===x.id);if(!s){fav=[{...x,collections:['all',id],savedAt:Date.now()},...fav]}else{s.collections=[...(s.collections||['all']).filter(v=>v!==id),...(s.collections||[]).includes(id)?[]:[id]];if(!s.collections.includes('all'))s.collections.unshift('all')}save();m.remove();shell(favoritesPage())});m.querySelector('#newc')!.addEventListener('click',()=>{const n=prompt('新分类名称');if(n){const before=getCollections();addCollection(n);const after=getCollections();const created=after.find(c=>!before.some(b=>b.id===c.id));if(created){if(!favd(x.id))fav=[{...x,collections:['all',created.id],savedAt:Date.now()},...fav];else fav.find(y=>y.id===x.id)!.collections=[...(fav.find(y=>y.id===x.id)!.collections||['all']),created.id];save()}m.remove();shell(favoritesPage())}})}
function preview(x:Saved){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-bg"></div><div class="modal-box"><button class="close">×</button><img src="${esc(x.image)}"><div><strong>${esc(x.title)}</strong><small>${esc(x.source||'Openverse')}${x.author?' · '+esc(x.author):''}${x.license?' · '+esc(x.license):''}</small><div class="modal-actions"><button id="mf">${favd(x.id)?'★ 已收藏':'☆ 收藏'}</button><button id="ma">📁 分类</button><button id="md">⬇ 下载</button><button id="mc">🔗 复制图片地址</button><button id="ms">↗ 查看来源</button></div></div></div>`;document.body.appendChild(m);m.querySelector('.close')!.addEventListener('click',()=>m.remove());m.querySelector('.modal-bg')!.addEventListener('click',()=>m.remove());m.querySelector('#mf')!.addEventListener('click',()=>{toggle(x);m.remove();shell(favoritesPage())});m.querySelector('#ma')!.addEventListener('click',()=>{m.remove();if(!favd(x.id))toggle(x);assignCollection(x)});m.querySelector('#md')!.addEventListener('click',async()=>{try{await downloadImage(x.image,`${x.title||'material-hub'}.jpg`)}catch{alert('下载失败，请尝试打开原图后保存')}});m.querySelector('#mc')!.addEventListener('click',async()=>{try{await copyImageUrl(x.image);alert('图片地址已复制')}catch{alert('复制失败')}});m.querySelector('#ms')!.addEventListener('click',()=>window.open(x.page||x.image,'_blank'))}
function contextMenu(x:Saved,ev:MouseEvent){ev.preventDefault();document.querySelector('.ctx')?.remove();const menu=document.createElement('div');menu.className='ctx';menu.style.left=`${Math.min(ev.clientX,innerWidth-215)}px`;menu.style.top=`${Math.min(ev.clientY,innerHeight-245)}px`;menu.innerHTML=`<button data-c="fav">${favd(x.id)?'★ 取消收藏':'☆ 收藏图片'}</button><button data-c="collection">📁 收藏到分类</button><button data-c="download">⬇ 下载图片</button><button data-c="copy">🔗 复制图片地址</button><button data-c="preview">🔍 大图预览</button><button data-c="source">↗ 打开素材来源</button>`;document.body.appendChild(menu);menu.onclick=async e=>{const a=(e.target as HTMLElement).closest('button');if(!a)return;const action=a.dataset.c;menu.remove();if(action==='fav'){toggle(x);document.querySelectorAll(`[data-fav="${CSS.escape(x.id)}"]`).forEach(b=>{b.textContent=favd(x.id)?'★':'☆';b.classList.toggle('on',favd(x.id))})}if(action==='collection'){if(!favd(x.id))toggle(x);assignCollection(x)}if(action==='download'){try{await downloadImage(x.image,`${x.title||'material-hub'}.jpg`)}catch{alert('下载失败，请尝试打开原图后保存')}}if(action==='copy'){try{await copyImageUrl(x.image);alert('图片地址已复制')}catch{alert('复制失败')}}if(action==='preview')preview(x);if(action==='source')window.open(x.page||x.image,'_blank')};setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0)}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.onclick=()=>{const p=b.dataset.page!;document.querySelector('#body')!.innerHTML=p==='search'?searchPage():p==='favorites'?favoritesPage():p==='history'?historyPage():sitesPage();bindBody()});document.querySelector('#go')?.addEventListener('click',()=>search(true));document.querySelector('#q')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(true)});document.querySelector('#theme')?.addEventListener('click',()=>{theme=theme==='light'?'dark':'light';save();shell(searchPage())});bindBody()}
function bindBody(){document.querySelectorAll<HTMLInputElement>('[data-site]').forEach(x=>x.onchange=()=>{sites[+x.dataset.site!].enabled=x.checked;save()});document.querySelectorAll<HTMLButtonElement>('[data-q]').forEach(b=>b.onclick=()=>{q=b.dataset.q!;shell(searchPage());search(true)});document.querySelectorAll<HTMLButtonElement>('[data-h]').forEach(b=>b.onclick=()=>{q=b.dataset.h!;shell(searchPage());search(true)});document.querySelectorAll<HTMLButtonElement>('[data-col]').forEach(b=>b.onclick=()=>{collection=b.dataset.col!;shell(favoritesPage())});document.querySelector('#newcol')?.addEventListener('click',()=>{const n=prompt('新分类名称');if(n){addCollection(n);shell(favoritesPage())}});document.querySelectorAll<HTMLButtonElement>('[data-fav]').forEach(b=>b.onclick=()=>{toggle(itemFromCard(b.closest('.image-card')!));b.textContent=favd(b.dataset.fav!)?'★':'☆';b.classList.toggle('on',favd(b.dataset.fav!))});document.querySelectorAll<HTMLButtonElement>('[data-openimg]').forEach(b=>{const x=itemFromCard(b.closest('.image-card')!);b.onclick=()=>preview(x);b.oncontextmenu=e=>contextMenu(x,e)});document.querySelectorAll<HTMLElement>('.image-card').forEach(c=>c.oncontextmenu=e=>contextMenu(itemFromCard(c),e));document.querySelector('#more')?.addEventListener('click',()=>{page++;search(false)});document.querySelectorAll<HTMLInputElement>('[data-toggle]').forEach(x=>x.onchange=()=>{sites[+x.dataset.toggle!].enabled=x.checked;save()});document.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>{sites.splice(+b.dataset.remove!,1);save();shell(sitesPage())});document.querySelector('#add')?.addEventListener('click',()=>{const n=(document.querySelector('#sn') as HTMLInputElement).value.trim(),u=(document.querySelector('#su') as HTMLInputElement).value.trim(),s=(document.querySelector('#ss') as HTMLInputElement).value.trim();if(n&&u&&s){sites.push({id:crypto.randomUUID(),name:n,url:u,search:s,enabled:true});save();shell(sitesPage())}})}
shell(searchPage());